### PR TITLE
updated styles to WCAG2.0 AA compliant text/link colors thanks to user feedback

### PR DESCRIPTION
**Pull request by jdkunesh**
@nicklucius @levyj @Chicago/open-data @danielledumerer
pls check it out & ok if ready. It's a non-breaking change to improve color contrast.

### CODE REVIEW

**Comment by levyj** [comment]
For historical reference: https://twitter.com/jimcraner/status/1116775856393936901

**Comment by jdkunesh** [comment]
Btw, the ci/push will never complete b/c this branch does not match the naming convention for being deployed. ie– it's ok.

**Comment by levyj** [comment]
Ok with me and I will merge if @danielledumerer is good with it. This seems pretty non-controversial but we should have some process to it.

**Comment by levyj** [comment]
I think I understand most of those words in isolation. 😊

**Comment by jdkunesh** [comment]
I thought the Travis command was getting hung up but it was actually just a little slow in resolving. So please ignore. That’s why I deleted the comment. TGIF!

@jdkunesh
312-925-7533

**Comment by levyj** [comment]
Verbally approved by @danielledumerer.

**Pull request merged**
