### PR TITLE
slight editing for clarity.

### PR DESCRIPTION
**Pull request by jdkunesh**
great work!

### CODE REVIEW

**Review by levyj — COMMENTED** [review]
Thanks, @jdkunesh. It does flow better but might it imply that we previously announced this exception, as opposed to this being a change from what we previously announced?

**Comment by jdkunesh** [comment]
I don't close read that strongly, but YMMV.

¯\_(ツ)_/¯

You wrote it, so go with the one you feel more comfortable with.
I trust you know what you want to communicate and how your audience is
likely to parse it.

**Comment by levyj** [comment]
I don't actually have that much sense of how people read these things (or even _if_ they read them). So, I will think about it. Also, and probably more important, I think some others are going to weigh in so I will see if they have similar comments.

Thanks for the review -- and particularly for playing along and making your suggested edit in the form of a pull request!

**Comment by levyj** [comment]
I actually cannot recall what became of this. I think I used some/all of the content without formally merging for some reason. Regardless, the post is live and I am just cleaning up so it is what it is.

**Pull request closed without merging**
