### PR TITLE
Create 2017-10-24-taxi-data-behind.md

### PR DESCRIPTION
**Pull request by levyj**
We probably should put something out about the taxi data. I tried to keep it pretty simple and not stir up too much but definitely am open to edits.

### CODE REVIEW

**Comment by levyj** [comment]
@tomschenkjr - It hardly is time-sensitive but this post has not appeared yet.  It looks like all checks were successful so maybe something downstream failed?

**Comment by tomschenkjr** [comment]
I reran the build and appeared to fix it.

**Comment by levyj** [comment]
Yes, I see it now.


I did not see a tweet, though. Is that still set up?


________________________________

**Comment by tomschenkjr** [comment]
That will probably happen in a few minutes (IFTT sometimes has a lag).

**Pull request merged**
