### PR TITLE
Fix broken link in open311 rotating image

### LINKED ISSUE #59: Broken link in open311 rotating image
The link in this image points to http://dev.cityofchicago.org/docs/api

I believe it should point to http://dev.cityofchicago.org/docs/open311/

image

### PR DESCRIPTION
**Pull request by diffractometer**
This PR (fixes https://github.com/Chicago/dev.cityofchicago.org/issues/59):

- Links to the reported correct link.

### CODE REVIEW

**Comment by geneorama** [comment]
For my own reference I used the following to check out the pull request:

```
git checkout -b request master
git pull https://github.com/diffractometer/dev.cityofchicago.org.git gh-pages
```

\<Spent about two hours installing Ruby and Jekyll and troubleshooting the Jekyll install\>

```
jekyll serve
```

Looks good to me, thanks @diffractometer.

Closes #59 

@levyj do you want to pull?

**Comment by diffractometer** [comment]
@geneorama Cool, I'm glad I can help, hope to contribute more soon, cheers.

**Comment by geneorama** [comment]
@levyj wondering if you wanted to pull this in?

**Comment by levyj** [comment]
Done. Thanks @geneorama and @diffractometer.

**Comment by diffractometer** [comment]
@levyj no prob glad to be of assistance

**Pull request merged**
